# Generated by Django 3.1.3 on 2022-05-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRecommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='city',
            field=models.CharField(default='0', max_length=70),
        ),
        migrations.AddField(
            model_name='rating',
            name='ip_address',
            field=models.GenericIPAddressField(default='192.168.0.1'),
        ),
        migrations.AddField(
            model_name='rating',
            name='lat',
            field=models.CharField(default='0', max_length=70),
        ),
        migrations.AddField(
            model_name='rating',
            name='lon',
            field=models.CharField(default='0', max_length=70),
        ),
    ]
